language: python
sudo: false
env:
  - python=2.7
    iris=v1.12.0

  - python=2.7
    iris=master

  - python=3.4
    iris=v1.12.0

  - python=3.4
    iris=master

install:
  # Fetch and install conda
  # -----------------------
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda3
  - wget ${CONDA_BASE}-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set show_channel_urls True
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda install --quiet --yes python=${python}

  # Install iris-grib's dependencies
  # --------------------------------
  - conda install --quiet --yes python-eccodes;
  - conda install --quiet --yes iris;

  # Install iris-grib itself
  # ------------------------
  - pip install . --no-deps

  # Install coveralls for test coverage
  # -----------------------------------
  - pip install coveralls

  # Summarise the environment
  # -------------------------
  - conda list

script:
  # Ensure we can import iris_grib and that the tests pass
  # ------------------------------------------------------
  - coverage run setup.py test

after_success: coveralls
